using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace OrchidMod
{
	public enum OrchidModMessageType : byte
	{
		SHAMANORBTYPECHANGEDSMALL,
		SHAMANORBTYPECHANGEDBIG,
		SHAMANORBTYPECHANGEDLARGE,
		SHAMANORBTYPECHANGEDUNIQUE,
		SHAMANORBTYPECHANGEDCIRCLE,
		SHAMANORBCOUNTCHANGEDSMALL,
		SHAMANORBCOUNTCHANGEDBIG,
		SHAMANORBCOUNTCHANGEDLARGE,
		SHAMANORBCOUNTCHANGEDUNIQUE,
		SHAMANORBCOUNTCHANGEDCIRCLE,
		SHAMANBUFFCHANGEDATTACK,
		SHAMANBUFFCHANGEDARMOR,
		SHAMANBUFFCHANGEDCRITICAL,
		SHAMANBUFFCHANGEDREGENERATION,
		SHAMANBUFFCHANGEDSPEED,
		SHAMANBUFFTIMERCHANGEDATTACK,
		SHAMANBUFFTIMERCHANGEDARMOR,
		SHAMANBUFFTIMERCHANGEDCRITICAL,
		SHAMANBUFFTIMERCHANGEDREGENERATION,
		SHAMANBUFFTIMERCHANGEDSPEED,
		
		GAMBLERCARDINDECKCHANGED,
		
		// ALCHEMISTELEMENTCHANGED0,
		// ALCHEMISTELEMENTCHANGED1,
		// ALCHEMISTELEMENTCHANGED2,
		// ALCHEMISTELEMENTCHANGED3,
		// ALCHEMISTELEMENTCHANGED4,
		// ALCHEMISTELEMENTCHANGED5,
		// ALCHEMISTFLASKCHANGED0,
		// ALCHEMISTFLASKCHANGED1,
		// ALCHEMISTFLASKCHANGED2,
		// ALCHEMISTFLASKCHANGED3,
		// ALCHEMISTFLASKCHANGED4,
		// ALCHEMISTFLASKCHANGED5,
		// ALCHEMISTDUSTCHANGED0,
		// ALCHEMISTDUSTCHANGED1,
		// ALCHEMISTDUSTCHANGED2,
		// ALCHEMISTDUSTCHANGED3,
		// ALCHEMISTDUSTCHANGED4,
		// ALCHEMISTDUSTCHANGED5,
		// ALCHEMISTCOLORCHANGEDR,
		// ALCHEMISTCOLORCHANGEDG,
		// ALCHEMISTCOLORCHANGEDB,
		
		ORCHIDPLAYERSYNCPLAYER
	}
}  