namespace OrchidMod.Alchemist
{
    public enum AlchemistHiddenReaction : int
    {
		NULL = 0,
		GLOWSHROOMHEALING = 1,
		FIRESPORES = 2,
		WATERSPORES = 3,
		AIRSPORES = 4,
		MUSHROOMTHREAD = 5,
		POTIONFLIPPER = 6,
		POTIONFEATHERFALL = 7,
		POTIONINVISIBILITY = 8,
		POTIONNIGHTOWL = 9,
		POTIONBUILDER = 10,
		PROPULSION = 11,
		BUBBLESLIME = 12,
		BUBBLESAP = 13,
		BUBBLESEAFOAM = 14,
		BUBBLEOIL = 15,
		BEESWARM = 16,
		BUBBLEPOISON = 17,
		BUBBLESPIRITED = 18,
		BUBBLES = 19,
		SUNFLOWERSEEDS = 20
    }
}  