namespace OrchidMod.Common
{
	public enum OrchidModMessageType : byte
	{
		GAMBLERCARDINDECKCHANGED,
		ORCHIDPLAYERSYNCPLAYERGAMBLER,
		NPCHITBYCLASS,
		SYNCONKILLNPC,
		SHAPESHIFTERAPPLYBLEEDTONPC
	}
}